spring:
  datasource:
    url: jdbc:h2:mem:test
    driver-class-name: org.h2.Driver
    username: sa
    password:
  file-root: resources/

jwt:
  issuer: spring-boot-demo
  secret: io.dycraft
  expires-in: 120 # in minutes
